### ISSUE TITLE
[3-Code generation] Empty Seq

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-lab#10]
Is Seq[  ] (nothing between [ and ]) a valid instruction?
If yes, what should it return?

**Comment by ymherklotz** [comment]
That is an interesting question, as it does not seem to be specified in the spec. I do not believe that it would be a valid instruction, as the spec mentions the return value being the instruction executed last. So if there are no instructions, there will be no return type. Therefore I do not think it will be tested either.

If the seq is empty, I think it would be fine to have the return value be the default `int32_t`. @johnwickerson may want to make the spec clearer on that though so I'll ask him about what he thinks should be the right behaviour.
