### ISSUE TITLE
[2-parsers] Unary operation

### ISSUE THREAD

**Issue by BenShen98** [LangProc/langproc-2018-lab#6]
For this spec, do we need to allow unary operator `+` `-` ?

* for example, would the following be valid?
  - `-abc`
  - `+abc`
  - `+2233`

  - And the possibel ambiguous `--1`: unary operator `-` perform on number `-1`

**Comment by johnwickerson** [comment]
No unary operators needed -- all the operators listed in the spec are binary operators. I've [updated the spec](https://github.com/LangProc/langproc-2018-lab/commit/15d337bd6b8a1e5415129aae0857ca2cc92aab36) to clarify this.
